package com.tzs.marshall.constants;

import java.util.Arrays;
import java.util.List;

public interface Constants {
    String USER = "USER";
    String ADMIN = "ADMIN";
    String DRIVER = "DRIVER";
    String TYPE_REGISTERED = "REGISTERED";
    List<String> ALLOWED_ROLES = Arrays.asList(USER, DRIVER);
    String SCHEMA = "marshall_service";
    Boolean isDeleted = Boolean.FALSE;
    Boolean isEnable = Boolean.TRUE;
    String OPEN = "OPEN";
    String CANCEL = "CANCEL";
    String BOOK = "BOOK";
    String START = "START";
    String REJECT = "REJECT";
    String ACCEPT = "ACCEPT";
    String CLOSE = "CLOSE";
    String AVAILABLE = "AVAILABLE";
    String ON_DUTY = "ON_DUTY";
    String OFF_DUTY = "OFF_DUTY";
    String NOT_SERVED = "NOT_SERVED";
    String PENDING = "PENDING";
    String PAID = "PAID";
    String QRCODE_DIR = "images/qrcodes";
    String IMAGE_TYPE = "image/jpeg,image/jpg,image/png";
    String BASE_PATH = "/var/marshall/docs/";
    String CONFIG_FILE = "config/";
    String DISCOUNT_CONFIG_FILE = "discount_config.json";
    String PASSWORD_REGEX = "PASSWORD_REGEX";
    String EMAIL_REGEX = "EMAIL_REGEX";
    String PASSWORD_LINK = "PASSWORD_RESET_LINK";
    String EMAIL_LINK = "EMAIL_CONFIRMATION_LINK";
    String SUPPORT_EMAIL = "SUPPORT_EMAIL";
    String PASSWORD_SUBJECT = "PASSWORD_SUBJECT";
    String EMAIL_SUBJECT = "EMAIL_SUBJECT";
    String PASSWORD_BODY = "PASSWORD_MAIL_BODY";
    String EMAIL_BODY = "EMAIL_MAIL_BODY";
    String ADMIN_EMAIL = "ADMIN_EMAIL";
    String ADMIN_EMAIL_PASSWORD = "ADMIN_EMAIL_PASSWORD";
    String CONTACT_US_EMAIL = "CONTACT_US_EMAIL";
    String QRCODE_UPLOADER = "QRCODE_UPLOADER";
    String UPLOAD_DIR = "UPLOAD_DIRECTORY";
    String FILE_FORMATS = "ALLOWED_FILE_FORMATS";
    String TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID";
    String TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN";
    String SUPPORT_MOBILE_NUMBER = "SUPPORT_MOBILE_NUMBER";
}
